services:
  template:
    image: template:humble
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        BASE_IMAGE: osrf/ros:humble-desktop-full
        ROS_DISTRO: humble
        USERNAME: ${USERNAME:-macs}
        UID: ${UID:-1000}
        GID: ${UID:-1000}
        VIDEO_GID: 44
        DIALOUT_GID: 20
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - XDG_RUNTIME_DIR=/tmp/runtime-${USERNAME:-macs}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./shared_ws:/workspaces/shared_ws:rw
      - ./data:/data:rw
      # REMOVE /dev/dri - that's for Intel
      - /dev:/dev
      - /tmp/runtime-${USERNAME:-macs}:/tmp/runtime-${USERNAME:-macs}:rw
    device_cgroup_rules:
      - 'c *:* rmw'
    # runtime: nvidia  # Add this!
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Changed from 1 to all
              capabilities: [gpu, utility, compute, graphics]  # Added graphics!
    # REMOVE the devices section with /dev/dri
    working_dir: /workspaces/shared_ws
    user: ${UID:-1000}:${UID:-1000}
    command: ["/bin/bash"]